parameters: 
- name: repoName 
  type: string
- name: pathToGeneratedModels
  type: string

steps:
- pwsh: '$(scriptsDirectory)/clean-java-files-kiota.ps1'
  displayName: 'Remove generated models and requests from the repo'
  env:
    MainDirectory: $(Build.SourcesDirectory)/${{ parameters.repoName }}/${{ parameters.pathToGeneratedModels }}

- pwsh: '$(scriptsDirectory)/copy-java-models-kiota.ps1'
  displayName: 'Update with new models'
  env: 
    BuildConfiguration: $(buildConfiguration) 
    OutputFullPath: $(kiotaDirectory)/output/*
    RepoModelsDir: $(Build.SourcesDirectory)/${{ parameters.repoName }}/${{ parameters.pathToGeneratedModels }}